// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ory/hydra/internal/httpclient/client/v1"
	"github.com/ory/hydra/internal/httpclient/models"
)

// AdminGetOAuth2ClientReader is a Reader for the AdminGetOAuth2Client structure.
type AdminGetOAuth2ClientReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AdminGetOAuth2ClientReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAdminGetOAuth2ClientOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAdminGetOAuth2ClientDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAdminGetOAuth2ClientOK creates a AdminGetOAuth2ClientOK with default headers values
func NewAdminGetOAuth2ClientOK() *AdminGetOAuth2ClientOK {
	return &AdminGetOAuth2ClientOK{}
}

/* AdminGetOAuth2ClientOK describes a response with status code 200, with default header values.

oAuth2Client
*/
type AdminGetOAuth2ClientOK struct {
	Payload *models.OAuth2Client
}

func (o *AdminGetOAuth2ClientOK) Error() string {
	return fmt.Sprintf("[GET /clients/{id}][%d] adminGetOAuth2ClientOK  %+v", 200, o.Payload)
}
func (o *AdminGetOAuth2ClientOK) GetPayload() *models.OAuth2Client {
	return o.Payload
}

func (o *AdminGetOAuth2ClientOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OAuth2Client)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAdminGetOAuth2ClientDefault creates a AdminGetOAuth2ClientDefault with default headers values
func NewAdminGetOAuth2ClientDefault(code int) *AdminGetOAuth2ClientDefault {
	return &AdminGetOAuth2ClientDefault{
		_statusCode: code,
	}
}

/* AdminGetOAuth2ClientDefault describes a response with status code -1, with default header values.

oAuth2ApiError
*/
type AdminGetOAuth2ClientDefault struct {
	_statusCode int

	Payload *models.OAuth2APIError
}

// Code gets the status code for the admin get o auth2 client default response
func (o *AdminGetOAuth2ClientDefault) Code() int {
	return o._statusCode
}

func (o *AdminGetOAuth2ClientDefault) Error() string {
	return fmt.Sprintf("[GET /clients/{id}][%d] adminGetOAuth2Client default  %+v", o._statusCode, o.Payload)
}
func (o *AdminGetOAuth2ClientDefault) GetPayload() *models.OAuth2APIError {
	return o.Payload
}

func (o *AdminGetOAuth2ClientDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OAuth2APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
