// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ory/hydra/internal/httpclient/models"
)

// NewUpdateOAuth2ClientLifespansParams creates a new UpdateOAuth2ClientLifespansParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateOAuth2ClientLifespansParams() *UpdateOAuth2ClientLifespansParams {
	return &UpdateOAuth2ClientLifespansParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateOAuth2ClientLifespansParamsWithTimeout creates a new UpdateOAuth2ClientLifespansParams object
// with the ability to set a timeout on a request.
func NewUpdateOAuth2ClientLifespansParamsWithTimeout(timeout time.Duration) *UpdateOAuth2ClientLifespansParams {
	return &UpdateOAuth2ClientLifespansParams{
		timeout: timeout,
	}
}

// NewUpdateOAuth2ClientLifespansParamsWithContext creates a new UpdateOAuth2ClientLifespansParams object
// with the ability to set a context for a request.
func NewUpdateOAuth2ClientLifespansParamsWithContext(ctx context.Context) *UpdateOAuth2ClientLifespansParams {
	return &UpdateOAuth2ClientLifespansParams{
		Context: ctx,
	}
}

// NewUpdateOAuth2ClientLifespansParamsWithHTTPClient creates a new UpdateOAuth2ClientLifespansParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateOAuth2ClientLifespansParamsWithHTTPClient(client *http.Client) *UpdateOAuth2ClientLifespansParams {
	return &UpdateOAuth2ClientLifespansParams{
		HTTPClient: client,
	}
}

/* UpdateOAuth2ClientLifespansParams contains all the parameters to send to the API endpoint
   for the update o auth2 client lifespans operation.

   Typically these are written to a http.Request.
*/
type UpdateOAuth2ClientLifespansParams struct {

	// Body.
	Body *models.UpdateOAuth2ClientLifespans

	/* ID.

	   The id of the OAuth 2.0 Client.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update o auth2 client lifespans params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateOAuth2ClientLifespansParams) WithDefaults() *UpdateOAuth2ClientLifespansParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update o auth2 client lifespans params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateOAuth2ClientLifespansParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update o auth2 client lifespans params
func (o *UpdateOAuth2ClientLifespansParams) WithTimeout(timeout time.Duration) *UpdateOAuth2ClientLifespansParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update o auth2 client lifespans params
func (o *UpdateOAuth2ClientLifespansParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update o auth2 client lifespans params
func (o *UpdateOAuth2ClientLifespansParams) WithContext(ctx context.Context) *UpdateOAuth2ClientLifespansParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update o auth2 client lifespans params
func (o *UpdateOAuth2ClientLifespansParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update o auth2 client lifespans params
func (o *UpdateOAuth2ClientLifespansParams) WithHTTPClient(client *http.Client) *UpdateOAuth2ClientLifespansParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update o auth2 client lifespans params
func (o *UpdateOAuth2ClientLifespansParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update o auth2 client lifespans params
func (o *UpdateOAuth2ClientLifespansParams) WithBody(body *models.UpdateOAuth2ClientLifespans) *UpdateOAuth2ClientLifespansParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update o auth2 client lifespans params
func (o *UpdateOAuth2ClientLifespansParams) SetBody(body *models.UpdateOAuth2ClientLifespans) {
	o.Body = body
}

// WithID adds the id to the update o auth2 client lifespans params
func (o *UpdateOAuth2ClientLifespansParams) WithID(id string) *UpdateOAuth2ClientLifespansParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update o auth2 client lifespans params
func (o *UpdateOAuth2ClientLifespansParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateOAuth2ClientLifespansParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
