FROM golang:1.8-alpine

RUN apk add --no-cache git && go get github.com/Masterminds/glide
WORKDIR /go/src/github.com/ory-am/hydra

ADD ./glide.yaml ./glide.yaml
ADD ./glide.lock ./glide.lock
RUN glide install --skip-test -v

ADD . .
RUN rm ./condition_string_pairs_equal.go
ADD ./condition_string_pairs_equal.go ./vendor/github.com/ory-am/ladon/condition_string_pairs_equal.go
RUN go install .

ENTRYPOINT /go/bin/hydra host --dangerous-force-http

EXPOSE 4444
