FROM golang:1.6

ADD . /go/src/github.com/ory-am/hydra
WORKDIR /go/src/github.com/ory-am/hydra

RUN go get github.com/Masterminds/glide
RUN glide install
RUN go install github.com/ory-am/hydra

ENTRYPOINT sleep 5; /go/bin/hydra host --dangerous-auto-logon

EXPOSE 4444