FROM golang:1.9-alpine

RUN apk add --no-cache git build-base
RUN go get github.com/Masterminds/glide
WORKDIR /go/src/github.com/ory/hydra

ADD ./glide.yaml ./glide.yaml
ADD ./glide.lock ./glide.lock
RUN glide install --skip-test -v

ADD . .
RUN go install .

ENTRYPOINT /go/bin/hydra migrate sql $DATABASE_URL

EXPOSE 4444