FROM golang:1.9-alpine

RUN apk add --no-cache git build-base curl
ENV DEP_VERSION 0.3.2
RUN curl -L -s https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -o $GOPATH/bin/dep
RUN chmod +x $GOPATH/bin/dep

WORKDIR /go/src/github.com/ory/hydra

ADD ./Gopkg.lock ./Gopkg.lock
ADD ./Gopkg.toml ./Gopkg.toml
RUN dep ensure -vendor-only

ADD . .
RUN go install .

ENTRYPOINT /go/bin/hydra migrate sql $DATABASE_URL

EXPOSE 4444