// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateDynOAuth2ClientParams creates a new CreateDynOAuth2ClientParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateDynOAuth2ClientParams() *CreateDynOAuth2ClientParams {
	return &CreateDynOAuth2ClientParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDynOAuth2ClientParamsWithTimeout creates a new CreateDynOAuth2ClientParams object
// with the ability to set a timeout on a request.
func NewCreateDynOAuth2ClientParamsWithTimeout(timeout time.Duration) *CreateDynOAuth2ClientParams {
	return &CreateDynOAuth2ClientParams{
		timeout: timeout,
	}
}

// NewCreateDynOAuth2ClientParamsWithContext creates a new CreateDynOAuth2ClientParams object
// with the ability to set a context for a request.
func NewCreateDynOAuth2ClientParamsWithContext(ctx context.Context) *CreateDynOAuth2ClientParams {
	return &CreateDynOAuth2ClientParams{
		Context: ctx,
	}
}

// NewCreateDynOAuth2ClientParamsWithHTTPClient creates a new CreateDynOAuth2ClientParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateDynOAuth2ClientParamsWithHTTPClient(client *http.Client) *CreateDynOAuth2ClientParams {
	return &CreateDynOAuth2ClientParams{
		HTTPClient: client,
	}
}

/* CreateDynOAuth2ClientParams contains all the parameters to send to the API endpoint
   for the create dyn o auth2 client operation.

   Typically these are written to a http.Request.
*/
type CreateDynOAuth2ClientParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create dyn o auth2 client params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDynOAuth2ClientParams) WithDefaults() *CreateDynOAuth2ClientParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create dyn o auth2 client params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDynOAuth2ClientParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create dyn o auth2 client params
func (o *CreateDynOAuth2ClientParams) WithTimeout(timeout time.Duration) *CreateDynOAuth2ClientParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create dyn o auth2 client params
func (o *CreateDynOAuth2ClientParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create dyn o auth2 client params
func (o *CreateDynOAuth2ClientParams) WithContext(ctx context.Context) *CreateDynOAuth2ClientParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create dyn o auth2 client params
func (o *CreateDynOAuth2ClientParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create dyn o auth2 client params
func (o *CreateDynOAuth2ClientParams) WithHTTPClient(client *http.Client) *CreateDynOAuth2ClientParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create dyn o auth2 client params
func (o *CreateDynOAuth2ClientParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDynOAuth2ClientParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
