// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ory/hydra/internal/httpclient/models"
)

// DynamicClientRegistrationUpdateOAuth2ClientReader is a Reader for the DynamicClientRegistrationUpdateOAuth2Client structure.
type DynamicClientRegistrationUpdateOAuth2ClientReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DynamicClientRegistrationUpdateOAuth2ClientReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDynamicClientRegistrationUpdateOAuth2ClientOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDynamicClientRegistrationUpdateOAuth2ClientDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDynamicClientRegistrationUpdateOAuth2ClientOK creates a DynamicClientRegistrationUpdateOAuth2ClientOK with default headers values
func NewDynamicClientRegistrationUpdateOAuth2ClientOK() *DynamicClientRegistrationUpdateOAuth2ClientOK {
	return &DynamicClientRegistrationUpdateOAuth2ClientOK{}
}

/* DynamicClientRegistrationUpdateOAuth2ClientOK describes a response with status code 200, with default header values.

oAuth2Client
*/
type DynamicClientRegistrationUpdateOAuth2ClientOK struct {
	Payload *models.OAuth2Client
}

func (o *DynamicClientRegistrationUpdateOAuth2ClientOK) Error() string {
	return fmt.Sprintf("[PUT /connect/register/{id}][%d] dynamicClientRegistrationUpdateOAuth2ClientOK  %+v", 200, o.Payload)
}
func (o *DynamicClientRegistrationUpdateOAuth2ClientOK) GetPayload() *models.OAuth2Client {
	return o.Payload
}

func (o *DynamicClientRegistrationUpdateOAuth2ClientOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OAuth2Client)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDynamicClientRegistrationUpdateOAuth2ClientDefault creates a DynamicClientRegistrationUpdateOAuth2ClientDefault with default headers values
func NewDynamicClientRegistrationUpdateOAuth2ClientDefault(code int) *DynamicClientRegistrationUpdateOAuth2ClientDefault {
	return &DynamicClientRegistrationUpdateOAuth2ClientDefault{
		_statusCode: code,
	}
}

/* DynamicClientRegistrationUpdateOAuth2ClientDefault describes a response with status code -1, with default header values.

jsonError
*/
type DynamicClientRegistrationUpdateOAuth2ClientDefault struct {
	_statusCode int

	Payload *models.JSONError
}

// Code gets the status code for the dynamic client registration update o auth2 client default response
func (o *DynamicClientRegistrationUpdateOAuth2ClientDefault) Code() int {
	return o._statusCode
}

func (o *DynamicClientRegistrationUpdateOAuth2ClientDefault) Error() string {
	return fmt.Sprintf("[PUT /connect/register/{id}][%d] dynamicClientRegistrationUpdateOAuth2Client default  %+v", o._statusCode, o.Payload)
}
func (o *DynamicClientRegistrationUpdateOAuth2ClientDefault) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *DynamicClientRegistrationUpdateOAuth2ClientDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
