ALTER TABLE hydra_oauth2_consent_request DROP COLUMN login_session_id;
ALTER TABLE hydra_oauth2_consent_request DROP COLUMN login_challenge;
ALTER TABLE hydra_oauth2_authentication_request DROP COLUMN login_session_id;
