-- Migration generated by the command below; DO NOT EDIT.
-- hydra:generate hydra migrate gen


-- hydra_oauth2_code
ALTER TABLE hydra_oauth2_code ADD COLUMN "nid" UUID;
ALTER TABLE hydra_oauth2_code ADD CONSTRAINT "hydra_oauth2_code_nid_fk_idx" FOREIGN KEY ("nid") REFERENCES "networks" ("id") ON UPDATE RESTRICT ON DELETE CASCADE;
