-- This is a blank migration. It is generated to ensure that all dialects are represented in the migration files.
-- ./hydra migrate gen ./persistence/sql/src/20220210000001_nid/ ./persistence/sql/migrations/
