-- Migration generated by the command below; DO NOT EDIT.
-- hydra:generate hydra migrate gen


ALTER TABLE hydra_client DROP COLUMN redirect_uris;
ALTER TABLE hydra_client DROP COLUMN grant_types;
ALTER TABLE hydra_client DROP COLUMN response_types;
ALTER TABLE hydra_client DROP COLUMN audience;
ALTER TABLE hydra_client DROP COLUMN allowed_cors_origins;
ALTER TABLE hydra_client DROP COLUMN contacts;
ALTER TABLE hydra_client DROP COLUMN request_uris;
ALTER TABLE hydra_client DROP COLUMN post_logout_redirect_uris;
