ALTER TABLE hydra_oauth2_flow
  DROP CONSTRAINT hydra_oauth2_flow_check,
  ALTER COLUMN requested_scope DROP NOT NULL,
  ALTER COLUMN login_csrf DROP NOT NULL,
  ALTER COLUMN subject DROP NOT NULL,
  ALTER COLUMN request_url DROP NOT NULL,
  ALTER COLUMN login_skip DROP NOT NULL,
  ALTER COLUMN client_id DROP NOT NULL,
  ALTER COLUMN oidc_context DROP NOT NULL,
  ALTER COLUMN context DROP NOT NULL,
  ALTER COLUMN state DROP NOT NULL,
  ALTER COLUMN login_verifier DROP NOT NULL,
  ALTER COLUMN login_remember DROP NOT NULL,
  ALTER COLUMN login_remember_for DROP NOT NULL,
  ALTER COLUMN acr DROP NOT NULL,
  ALTER COLUMN login_was_used DROP NOT NULL,
  ALTER COLUMN consent_skip DROP NOT NULL,
  ALTER COLUMN consent_remember DROP NOT NULL,
  ALTER COLUMN session_access_token DROP NOT NULL,
  ALTER COLUMN session_id_token DROP NOT NULL,
  ALTER COLUMN consent_was_used DROP NOT NULL;
