ALTER TABLE hydra_oauth2_flow
  DROP CONSTRAINT hydra_oauth2_flow_chk,
  MODIFY COLUMN requested_scope json NULL,
  MODIFY COLUMN login_csrf varchar(40) NULL,
  MODIFY COLUMN subject varchar(255) NULL,
  MODIFY COLUMN request_url text DEFAULT NULL,
  MODIFY COLUMN login_skip tinyint(1) NULL,
  MODIFY COLUMN client_id varchar(255) NULL,
  MODIFY COLUMN oidc_context json NULL,
  MODIFY COLUMN context json NULL,
  MODIFY COLUMN state smallint NULL,
  MODIFY COLUMN login_verifier varchar(40) NULL,
  MODIFY COLUMN login_remember tinyint(1) NULL,
  MODIFY COLUMN login_remember_for int NULL,
  MODIFY COLUMN acr text DEFAULT NULL,
  MODIFY COLUMN login_was_used tinyint(1) NULL,
  MODIFY COLUMN consent_skip tinyint(1) NULL,
  MODIFY COLUMN consent_remember tinyint(1) NULL,
  MODIFY COLUMN session_access_token json NULL,
  MODIFY COLUMN session_id_token json NULL,
  MODIFY COLUMN consent_was_used tinyint(1) NULL,

  -- Set default values to NULL for compatibility with strict SQL modes
  MODIFY COLUMN login_session_id varchar(40) DEFAULT NULL,
  MODIFY COLUMN login_error text DEFAULT NULL,
  MODIFY COLUMN consent_error text DEFAULT NULL,
  MODIFY COLUMN requested_at_audience json DEFAULT NULL,
  MODIFY COLUMN amr json DEFAULT NULL,
  MODIFY COLUMN granted_at_audience json DEFAULT NULL;
