ALTER TABLE hydra_oauth2_flow
  DROP CONSTRAINT check_state_state_state_state_login_remember_login_remember_for_login_error_acr_login_was_used_context_amr_state_login_remember_login_remember_for_login_error_acr_login_was_used_context_amr_state_login_remember_login_remember_for_login_error_acr_login_was_used_context_amr_consent_challenge_id_consent_verifier_consent_skip_consent_csrf_state_login_remember_login_remember_for_login_error_acr_login_was_used_context_amr_consent_challenge_id_consent_verifier_consent_skip_consent_csrf_state_login_remember_login_remember_for_login_error_acr_login_was_used_context_amr_consent_challenge_id_consent_verifier_consent_skip_consent_csrf_granted_scope_consent_remember_consent_remember_for_consent_error_session_access_token_session_id_token_consent_was_used,
  ALTER COLUMN requested_scope DROP NOT NULL,
  ALTER COLUMN login_csrf DROP NOT NULL,
  ALTER COLUMN subject DROP NOT NULL,
  ALTER COLUMN request_url DROP NOT NULL,
  ALTER COLUMN login_skip DROP NOT NULL,
  ALTER COLUMN client_id DROP NOT NULL,
  ALTER COLUMN oidc_context DROP NOT NULL,
  ALTER COLUMN context DROP NOT NULL,
  ALTER COLUMN state DROP NOT NULL,
  ALTER COLUMN login_verifier DROP NOT NULL,
  ALTER COLUMN login_remember DROP NOT NULL,
  ALTER COLUMN login_remember_for DROP NOT NULL,
  ALTER COLUMN acr DROP NOT NULL,
  ALTER COLUMN login_was_used DROP NOT NULL,
  ALTER COLUMN consent_skip DROP NOT NULL,
  ALTER COLUMN consent_remember DROP NOT NULL,
  ALTER COLUMN session_access_token DROP NOT NULL,
  ALTER COLUMN session_id_token DROP NOT NULL,
  ALTER COLUMN consent_was_used DROP NOT NULL;
