DROP TABLE "identity_credential_identifiers";COMMIT TRANSACTION;BEGIN TRANSACTION;
DROP TABLE "identity_credentials";COMMIT TRANSACTION;BEGIN TRANSACTION;
DROP TABLE "identity_credential_types";COMMIT TRANSACTION;BEGIN TRANSACTION;
DROP TABLE "identities";COMMIT TRANSACTION;BEGIN TRANSACTION;