FROM alpine:3.20 AS base-files

RUN <<HEREDOC
    apk upgrade --no-cache
    apk add --no-cache --upgrade ca-certificates

    # Add a user/group for Ory with a stable UID + GID:
    addgroup --system --gid 500 ory
    adduser --system --uid 500 \
      --gecos "Ory User" \
      --home /home/ory \
      --ingroup ory \
      --shell /sbin/nologin \
      ory

    # Create the sqlite directory with ownership to that user and group:
    # NOTE: This is required for read/write by SQLite.
    install --owner ory --group ory --directory /var/lib/sqlite
HEREDOC

FROM scratch
COPY --from=base-files /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=base-files /etc/nsswitch.conf /etc/nsswitch.conf
# NOTE: /etc/group and /etc/shadow were not copied over, only user lookup is valid for `USER`:
COPY --from=base-files /etc/passwd /etc/passwd
# NOTE: This COPY defaults to 0:0 for ownership, voiding the requirement conveyed above
COPY --from=base-files /var/lib/sqlite /var/lib/sqlite

COPY hydra /usr/bin/hydra

ENTRYPOINT ["hydra"]
CMD ["serve", "all"]
USER ory
