FROM golang:1.19 AS builder

RUN apt-get update && apt-get upgrade -y &&\
    mkdir -p /var/lib/sqlite

WORKDIR /go/src/github.com/ory/hydra

ENV GO111MODULE on
ENV CGO_ENABLED 1

COPY . .
RUN go mod download &&\
    go build -tags sqlite,json1 -o /usr/bin/hydra

#########################

FROM gcr.io/distroless/base:nonroot AS runner

COPY --from=builder --chown=nonroot:nonroot /var/lib/sqlite /var/lib/sqlite
COPY --from=builder /usr/bin/hydra /usr/bin/hydra

VOLUME /var/lib/sqlite

# Declare the standard ports used by hydra (4444 for public service endpoint, 4445 for admin service endpoint)
EXPOSE 4444 4445

ENTRYPOINT ["hydra"]
CMD ["serve", "all"]
