FROM alpine:3.20

RUN <<HEREDOC
    apk add --no-cache --upgrade ca-certificates

    # Add a user/group for Ory with a stable UID + GID:
    # NOTE: This only appears relevant for supporting hydra as non-root, otherwise unnecessary.
    addgroup --system --gid 65532 ory
    adduser --system --uid 65532 \
      --gecos "Ory User" \
      --home /home/ory \
      --ingroup ory \
      --shell /sbin/nologin \
      ory
HEREDOC

COPY hydra /usr/bin/hydra

USER ory

ENTRYPOINT ["hydra"]
CMD ["serve", "all"]
