FROM golang:1.19-alpine3.18 AS builder

RUN apk -U --no-cache --upgrade --latest add build-base git gcc bash

WORKDIR /go/src/github.com/ory/hydra
RUN mkdir -p ./internal/httpclient

COPY go.mod go.sum ./
COPY internal/httpclient/go.* ./internal/httpclient/

ENV GO111MODULE on
ENV CGO_ENABLED 1

RUN go mod download

COPY . .

RUN go build -tags sqlite,json1 -o /usr/bin/hydra

#########################

FROM gcr.io/distroless/static-debian11:nonroot as runner

COPY --from=builder /usr/bin/hydra /usr/bin/hydra

# Declare the standard ports used by hydra (4444 for public service endpoint, 4445 for admin service endpoint)
EXPOSE 4444 4445

ENTRYPOINT ["/usr/bin/hydra"]
CMD ["serve"]
