FROM alpine:3.20

RUN <<HEREDOC
    apk upgrade --no-cache
    apk add --no-cache --upgrade ca-certificates

    # Add a user/group for Ory with a stable UID + GID:
    addgroup --system --gid 500 ory
    adduser --system --uid 500 \
      --gecos "Ory User" \
      --home /home/ory \
      --ingroup ory \
      --shell /sbin/nologin \
      ory

    # Create the sqlite directory with ownership to that user and group:
    # NOTE: This is required for read/write by SQLite.
    install --owner ory --group ory --directory /var/lib/sqlite
HEREDOC

COPY hydra /usr/bin/hydra

ENTRYPOINT ["hydra"]
CMD ["serve", "all"]
USER ory
