// Copyright © 2025 Ory Corp
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ory/hydra/v2/fosite/handler/oauth2 (interfaces: AuthorizeCodeStrategyProvider)
//
// Generated by this command:
//
//	mockgen -package internal -destination internal/authorize_code_strategy_provider.go github.com/ory/hydra/v2/fosite/handler/oauth2 AuthorizeCodeStrategyProvider
//

// Package internal is a generated GoMock package.
package internal

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	oauth2 "github.com/ory/hydra/v2/fosite/handler/oauth2"
)

// MockAuthorizeCodeStrategyProvider is a mock of AuthorizeCodeStrategyProvider interface.
type MockAuthorizeCodeStrategyProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizeCodeStrategyProviderMockRecorder
	isgomock struct{}
}

// MockAuthorizeCodeStrategyProviderMockRecorder is the mock recorder for MockAuthorizeCodeStrategyProvider.
type MockAuthorizeCodeStrategyProviderMockRecorder struct {
	mock *MockAuthorizeCodeStrategyProvider
}

// NewMockAuthorizeCodeStrategyProvider creates a new mock instance.
func NewMockAuthorizeCodeStrategyProvider(ctrl *gomock.Controller) *MockAuthorizeCodeStrategyProvider {
	mock := &MockAuthorizeCodeStrategyProvider{ctrl: ctrl}
	mock.recorder = &MockAuthorizeCodeStrategyProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizeCodeStrategyProvider) EXPECT() *MockAuthorizeCodeStrategyProviderMockRecorder {
	return m.recorder
}

// AuthorizeCodeStrategy mocks base method.
func (m *MockAuthorizeCodeStrategyProvider) AuthorizeCodeStrategy() oauth2.AuthorizeCodeStrategy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthorizeCodeStrategy")
	ret0, _ := ret[0].(oauth2.AuthorizeCodeStrategy)
	return ret0
}

// AuthorizeCodeStrategy indicates an expected call of AuthorizeCodeStrategy.
func (mr *MockAuthorizeCodeStrategyProviderMockRecorder) AuthorizeCodeStrategy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizeCodeStrategy", reflect.TypeOf((*MockAuthorizeCodeStrategyProvider)(nil).AuthorizeCodeStrategy))
}
