// Copyright © 2025 Ory Corp
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ory/hydra/v2/fosite/handler/oauth2 (interfaces: CoreStorage)
//
// Generated by this command:
//
//	mockgen -package internal -destination internal/oauth2_storage.go github.com/ory/hydra/v2/fosite/handler/oauth2 CoreStorage
//

// Package internal is a generated GoMock package.
package internal

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	oauth2 "github.com/ory/hydra/v2/fosite/handler/oauth2"
)

// MockCoreStorage is a mock of CoreStorage interface.
type MockCoreStorage struct {
	ctrl     *gomock.Controller
	recorder *MockCoreStorageMockRecorder
	isgomock struct{}
}

// MockCoreStorageMockRecorder is the mock recorder for MockCoreStorage.
type MockCoreStorageMockRecorder struct {
	mock *MockCoreStorage
}

// NewMockCoreStorage creates a new mock instance.
func NewMockCoreStorage(ctrl *gomock.Controller) *MockCoreStorage {
	mock := &MockCoreStorage{ctrl: ctrl}
	mock.recorder = &MockCoreStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoreStorage) EXPECT() *MockCoreStorageMockRecorder {
	return m.recorder
}

// AccessTokenStorage mocks base method.
func (m *MockCoreStorage) AccessTokenStorage() oauth2.AccessTokenStorage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessTokenStorage")
	ret0, _ := ret[0].(oauth2.AccessTokenStorage)
	return ret0
}

// AccessTokenStorage indicates an expected call of AccessTokenStorage.
func (mr *MockCoreStorageMockRecorder) AccessTokenStorage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessTokenStorage", reflect.TypeOf((*MockCoreStorage)(nil).AccessTokenStorage))
}

// AuthorizeCodeStorage mocks base method.
func (m *MockCoreStorage) AuthorizeCodeStorage() oauth2.AuthorizeCodeStorage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthorizeCodeStorage")
	ret0, _ := ret[0].(oauth2.AuthorizeCodeStorage)
	return ret0
}

// AuthorizeCodeStorage indicates an expected call of AuthorizeCodeStorage.
func (mr *MockCoreStorageMockRecorder) AuthorizeCodeStorage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizeCodeStorage", reflect.TypeOf((*MockCoreStorage)(nil).AuthorizeCodeStorage))
}

// RefreshTokenStorage mocks base method.
func (m *MockCoreStorage) RefreshTokenStorage() oauth2.RefreshTokenStorage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokenStorage")
	ret0, _ := ret[0].(oauth2.RefreshTokenStorage)
	return ret0
}

// RefreshTokenStorage indicates an expected call of RefreshTokenStorage.
func (mr *MockCoreStorageMockRecorder) RefreshTokenStorage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokenStorage", reflect.TypeOf((*MockCoreStorage)(nil).RefreshTokenStorage))
}
