// Copyright © 2025 Ory Corp
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ory/hydra/v2/fosite/handler/rfc8628 (interfaces: UserCodeStrategyProvider)
//
// Generated by this command:
//
//	mockgen -package internal -destination internal/user_code_strategy_provider.go github.com/ory/hydra/v2/fosite/handler/rfc8628 UserCodeStrategyProvider
//

// Package internal is a generated GoMock package.
package internal

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	rfc8628 "github.com/ory/hydra/v2/fosite/handler/rfc8628"
)

// MockUserCodeStrategyProvider is a mock of UserCodeStrategyProvider interface.
type MockUserCodeStrategyProvider struct {
	ctrl     *gomock.Controller
	recorder *MockUserCodeStrategyProviderMockRecorder
	isgomock struct{}
}

// MockUserCodeStrategyProviderMockRecorder is the mock recorder for MockUserCodeStrategyProvider.
type MockUserCodeStrategyProviderMockRecorder struct {
	mock *MockUserCodeStrategyProvider
}

// NewMockUserCodeStrategyProvider creates a new mock instance.
func NewMockUserCodeStrategyProvider(ctrl *gomock.Controller) *MockUserCodeStrategyProvider {
	mock := &MockUserCodeStrategyProvider{ctrl: ctrl}
	mock.recorder = &MockUserCodeStrategyProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCodeStrategyProvider) EXPECT() *MockUserCodeStrategyProviderMockRecorder {
	return m.recorder
}

// UserCodeStrategy mocks base method.
func (m *MockUserCodeStrategyProvider) UserCodeStrategy() rfc8628.UserCodeStrategy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserCodeStrategy")
	ret0, _ := ret[0].(rfc8628.UserCodeStrategy)
	return ret0
}

// UserCodeStrategy indicates an expected call of UserCodeStrategy.
func (mr *MockUserCodeStrategyProviderMockRecorder) UserCodeStrategy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserCodeStrategy", reflect.TypeOf((*MockUserCodeStrategyProvider)(nil).UserCodeStrategy))
}
