// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ory/hydra/client (interfaces: Configuration)

// Package internal is a generated GoMock package.
package internal

import (
	url "net/url"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"

	tracing "github.com/ory/hydra/tracing"
)

// MockClientConfiguration is a mock of Configuration interface
type MockClientConfiguration struct {
	ctrl     *gomock.Controller
	recorder *MockClientConfigurationMockRecorder
}

// MockClientConfigurationMockRecorder is the mock recorder for MockClientConfiguration
type MockClientConfigurationMockRecorder struct {
	mock *MockClientConfiguration
}

// NewMockClientConfiguration creates a new mock instance
func NewMockClientConfiguration(ctrl *gomock.Controller) *MockClientConfiguration {
	mock := &MockClientConfiguration{ctrl: ctrl}
	mock.recorder = &MockClientConfigurationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClientConfiguration) EXPECT() *MockClientConfigurationMockRecorder {
	return m.recorder
}

// AccessTokenLifespan mocks base method
func (m *MockClientConfiguration) AccessTokenLifespan() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessTokenLifespan")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// AccessTokenLifespan indicates an expected call of AccessTokenLifespan
func (mr *MockClientConfigurationMockRecorder) AccessTokenLifespan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessTokenLifespan", reflect.TypeOf((*MockClientConfiguration)(nil).AccessTokenLifespan))
}

// AccessTokenStrategy mocks base method
func (m *MockClientConfiguration) AccessTokenStrategy() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessTokenStrategy")
	ret0, _ := ret[0].(string)
	return ret0
}

// AccessTokenStrategy indicates an expected call of AccessTokenStrategy
func (mr *MockClientConfigurationMockRecorder) AccessTokenStrategy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessTokenStrategy", reflect.TypeOf((*MockClientConfiguration)(nil).AccessTokenStrategy))
}

// AdminListenOn mocks base method
func (m *MockClientConfiguration) AdminListenOn() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminListenOn")
	ret0, _ := ret[0].(string)
	return ret0
}

// AdminListenOn indicates an expected call of AdminListenOn
func (mr *MockClientConfigurationMockRecorder) AdminListenOn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminListenOn", reflect.TypeOf((*MockClientConfiguration)(nil).AdminListenOn))
}

// AdminURL mocks base method
func (m *MockClientConfiguration) AdminURL() *url.URL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminURL")
	ret0, _ := ret[0].(*url.URL)
	return ret0
}

// AdminURL indicates an expected call of AdminURL
func (mr *MockClientConfigurationMockRecorder) AdminURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminURL", reflect.TypeOf((*MockClientConfiguration)(nil).AdminURL))
}

// AllowTLSTerminationFrom mocks base method
func (m *MockClientConfiguration) AllowTLSTerminationFrom() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllowTLSTerminationFrom")
	ret0, _ := ret[0].([]string)
	return ret0
}

// AllowTLSTerminationFrom indicates an expected call of AllowTLSTerminationFrom
func (mr *MockClientConfigurationMockRecorder) AllowTLSTerminationFrom() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowTLSTerminationFrom", reflect.TypeOf((*MockClientConfiguration)(nil).AllowTLSTerminationFrom))
}

// AuthCodeLifespan mocks base method
func (m *MockClientConfiguration) AuthCodeLifespan() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthCodeLifespan")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// AuthCodeLifespan indicates an expected call of AuthCodeLifespan
func (mr *MockClientConfigurationMockRecorder) AuthCodeLifespan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthCodeLifespan", reflect.TypeOf((*MockClientConfiguration)(nil).AuthCodeLifespan))
}

// BCryptCost mocks base method
func (m *MockClientConfiguration) BCryptCost() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BCryptCost")
	ret0, _ := ret[0].(int)
	return ret0
}

// BCryptCost indicates an expected call of BCryptCost
func (mr *MockClientConfigurationMockRecorder) BCryptCost() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BCryptCost", reflect.TypeOf((*MockClientConfiguration)(nil).BCryptCost))
}

// ConsentRequestMaxAge mocks base method
func (m *MockClientConfiguration) ConsentRequestMaxAge() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsentRequestMaxAge")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// ConsentRequestMaxAge indicates an expected call of ConsentRequestMaxAge
func (mr *MockClientConfigurationMockRecorder) ConsentRequestMaxAge() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsentRequestMaxAge", reflect.TypeOf((*MockClientConfiguration)(nil).ConsentRequestMaxAge))
}

// ConsentURL mocks base method
func (m *MockClientConfiguration) ConsentURL() *url.URL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsentURL")
	ret0, _ := ret[0].(*url.URL)
	return ret0
}

// ConsentURL indicates an expected call of ConsentURL
func (mr *MockClientConfigurationMockRecorder) ConsentURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsentURL", reflect.TypeOf((*MockClientConfiguration)(nil).ConsentURL))
}

// DSN mocks base method
func (m *MockClientConfiguration) DSN() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DSN")
	ret0, _ := ret[0].(string)
	return ret0
}

// DSN indicates an expected call of DSN
func (mr *MockClientConfigurationMockRecorder) DSN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DSN", reflect.TypeOf((*MockClientConfiguration)(nil).DSN))
}

// DataSourcePlugin mocks base method
func (m *MockClientConfiguration) DataSourcePlugin() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataSourcePlugin")
	ret0, _ := ret[0].(string)
	return ret0
}

// DataSourcePlugin indicates an expected call of DataSourcePlugin
func (mr *MockClientConfigurationMockRecorder) DataSourcePlugin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataSourcePlugin", reflect.TypeOf((*MockClientConfiguration)(nil).DataSourcePlugin))
}

// DefaultClientScope mocks base method
func (m *MockClientConfiguration) DefaultClientScope() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultClientScope")
	ret0, _ := ret[0].([]string)
	return ret0
}

// DefaultClientScope indicates an expected call of DefaultClientScope
func (mr *MockClientConfigurationMockRecorder) DefaultClientScope() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultClientScope", reflect.TypeOf((*MockClientConfiguration)(nil).DefaultClientScope))
}

// ErrorURL mocks base method
func (m *MockClientConfiguration) ErrorURL() *url.URL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ErrorURL")
	ret0, _ := ret[0].(*url.URL)
	return ret0
}

// ErrorURL indicates an expected call of ErrorURL
func (mr *MockClientConfigurationMockRecorder) ErrorURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorURL", reflect.TypeOf((*MockClientConfiguration)(nil).ErrorURL))
}

// GetCookieSecrets mocks base method
func (m *MockClientConfiguration) GetCookieSecrets() [][]byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCookieSecrets")
	ret0, _ := ret[0].([][]byte)
	return ret0
}

// GetCookieSecrets indicates an expected call of GetCookieSecrets
func (mr *MockClientConfigurationMockRecorder) GetCookieSecrets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCookieSecrets", reflect.TypeOf((*MockClientConfiguration)(nil).GetCookieSecrets))
}

// GetRotatedSystemSecrets mocks base method
func (m *MockClientConfiguration) GetRotatedSystemSecrets() [][]byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRotatedSystemSecrets")
	ret0, _ := ret[0].([][]byte)
	return ret0
}

// GetRotatedSystemSecrets indicates an expected call of GetRotatedSystemSecrets
func (mr *MockClientConfigurationMockRecorder) GetRotatedSystemSecrets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRotatedSystemSecrets", reflect.TypeOf((*MockClientConfiguration)(nil).GetRotatedSystemSecrets))
}

// GetSystemSecret mocks base method
func (m *MockClientConfiguration) GetSystemSecret() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemSecret")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetSystemSecret indicates an expected call of GetSystemSecret
func (mr *MockClientConfigurationMockRecorder) GetSystemSecret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemSecret", reflect.TypeOf((*MockClientConfiguration)(nil).GetSystemSecret))
}

// IDTokenLifespan mocks base method
func (m *MockClientConfiguration) IDTokenLifespan() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IDTokenLifespan")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// IDTokenLifespan indicates an expected call of IDTokenLifespan
func (mr *MockClientConfigurationMockRecorder) IDTokenLifespan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IDTokenLifespan", reflect.TypeOf((*MockClientConfiguration)(nil).IDTokenLifespan))
}

// IssuerURL mocks base method
func (m *MockClientConfiguration) IssuerURL() *url.URL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssuerURL")
	ret0, _ := ret[0].(*url.URL)
	return ret0
}

// IssuerURL indicates an expected call of IssuerURL
func (mr *MockClientConfigurationMockRecorder) IssuerURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssuerURL", reflect.TypeOf((*MockClientConfiguration)(nil).IssuerURL))
}

// LoginURL mocks base method
func (m *MockClientConfiguration) LoginURL() *url.URL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginURL")
	ret0, _ := ret[0].(*url.URL)
	return ret0
}

// LoginURL indicates an expected call of LoginURL
func (mr *MockClientConfigurationMockRecorder) LoginURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginURL", reflect.TypeOf((*MockClientConfiguration)(nil).LoginURL))
}

// LogoutRedirectURL mocks base method
func (m *MockClientConfiguration) LogoutRedirectURL() *url.URL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogoutRedirectURL")
	ret0, _ := ret[0].(*url.URL)
	return ret0
}

// LogoutRedirectURL indicates an expected call of LogoutRedirectURL
func (mr *MockClientConfigurationMockRecorder) LogoutRedirectURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogoutRedirectURL", reflect.TypeOf((*MockClientConfiguration)(nil).LogoutRedirectURL))
}

// OAuth2AuthURL mocks base method
func (m *MockClientConfiguration) OAuth2AuthURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OAuth2AuthURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// OAuth2AuthURL indicates an expected call of OAuth2AuthURL
func (mr *MockClientConfigurationMockRecorder) OAuth2AuthURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OAuth2AuthURL", reflect.TypeOf((*MockClientConfiguration)(nil).OAuth2AuthURL))
}

// OAuth2ClientRegistrationURL mocks base method
func (m *MockClientConfiguration) OAuth2ClientRegistrationURL() *url.URL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OAuth2ClientRegistrationURL")
	ret0, _ := ret[0].(*url.URL)
	return ret0
}

// OAuth2ClientRegistrationURL indicates an expected call of OAuth2ClientRegistrationURL
func (mr *MockClientConfigurationMockRecorder) OAuth2ClientRegistrationURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OAuth2ClientRegistrationURL", reflect.TypeOf((*MockClientConfiguration)(nil).OAuth2ClientRegistrationURL))
}

// OIDCDiscoverySupportedScope mocks base method
func (m *MockClientConfiguration) OIDCDiscoverySupportedScope() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OIDCDiscoverySupportedScope")
	ret0, _ := ret[0].([]string)
	return ret0
}

// OIDCDiscoverySupportedScope indicates an expected call of OIDCDiscoverySupportedScope
func (mr *MockClientConfigurationMockRecorder) OIDCDiscoverySupportedScope() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OIDCDiscoverySupportedScope", reflect.TypeOf((*MockClientConfiguration)(nil).OIDCDiscoverySupportedScope))
}

// OIDCDiscoveryUserinfoEndpoint mocks base method
func (m *MockClientConfiguration) OIDCDiscoveryUserinfoEndpoint() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OIDCDiscoveryUserinfoEndpoint")
	ret0, _ := ret[0].(string)
	return ret0
}

// OIDCDiscoveryUserinfoEndpoint indicates an expected call of OIDCDiscoveryUserinfoEndpoint
func (mr *MockClientConfigurationMockRecorder) OIDCDiscoveryUserinfoEndpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OIDCDiscoveryUserinfoEndpoint", reflect.TypeOf((*MockClientConfiguration)(nil).OIDCDiscoveryUserinfoEndpoint))
}

// PublicListenOn mocks base method
func (m *MockClientConfiguration) PublicListenOn() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicListenOn")
	ret0, _ := ret[0].(string)
	return ret0
}

// PublicListenOn indicates an expected call of PublicListenOn
func (mr *MockClientConfigurationMockRecorder) PublicListenOn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicListenOn", reflect.TypeOf((*MockClientConfiguration)(nil).PublicListenOn))
}

// PublicURL mocks base method
func (m *MockClientConfiguration) PublicURL() *url.URL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicURL")
	ret0, _ := ret[0].(*url.URL)
	return ret0
}

// PublicURL indicates an expected call of PublicURL
func (mr *MockClientConfigurationMockRecorder) PublicURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicURL", reflect.TypeOf((*MockClientConfiguration)(nil).PublicURL))
}

// RefreshTokenLifespan mocks base method
func (m *MockClientConfiguration) RefreshTokenLifespan() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokenLifespan")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// RefreshTokenLifespan indicates an expected call of RefreshTokenLifespan
func (mr *MockClientConfigurationMockRecorder) RefreshTokenLifespan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokenLifespan", reflect.TypeOf((*MockClientConfiguration)(nil).RefreshTokenLifespan))
}

// ScopeStrategy mocks base method
func (m *MockClientConfiguration) ScopeStrategy() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScopeStrategy")
	ret0, _ := ret[0].(string)
	return ret0
}

// ScopeStrategy indicates an expected call of ScopeStrategy
func (mr *MockClientConfigurationMockRecorder) ScopeStrategy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScopeStrategy", reflect.TypeOf((*MockClientConfiguration)(nil).ScopeStrategy))
}

// ShareOAuth2Debug mocks base method
func (m *MockClientConfiguration) ShareOAuth2Debug() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShareOAuth2Debug")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShareOAuth2Debug indicates an expected call of ShareOAuth2Debug
func (mr *MockClientConfigurationMockRecorder) ShareOAuth2Debug() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShareOAuth2Debug", reflect.TypeOf((*MockClientConfiguration)(nil).ShareOAuth2Debug))
}

// SubjectIdentifierAlgorithmSalt mocks base method
func (m *MockClientConfiguration) SubjectIdentifierAlgorithmSalt() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubjectIdentifierAlgorithmSalt")
	ret0, _ := ret[0].(string)
	return ret0
}

// SubjectIdentifierAlgorithmSalt indicates an expected call of SubjectIdentifierAlgorithmSalt
func (mr *MockClientConfigurationMockRecorder) SubjectIdentifierAlgorithmSalt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubjectIdentifierAlgorithmSalt", reflect.TypeOf((*MockClientConfiguration)(nil).SubjectIdentifierAlgorithmSalt))
}

// SubjectTypesSupported mocks base method
func (m *MockClientConfiguration) SubjectTypesSupported() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubjectTypesSupported")
	ret0, _ := ret[0].([]string)
	return ret0
}

// SubjectTypesSupported indicates an expected call of SubjectTypesSupported
func (mr *MockClientConfigurationMockRecorder) SubjectTypesSupported() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubjectTypesSupported", reflect.TypeOf((*MockClientConfiguration)(nil).SubjectTypesSupported))
}

// TracingJaegerConfig mocks base method
func (m *MockClientConfiguration) TracingJaegerConfig() *tracing.JaegerConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TracingJaegerConfig")
	ret0, _ := ret[0].(*tracing.JaegerConfig)
	return ret0
}

// TracingJaegerConfig indicates an expected call of TracingJaegerConfig
func (mr *MockClientConfigurationMockRecorder) TracingJaegerConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TracingJaegerConfig", reflect.TypeOf((*MockClientConfiguration)(nil).TracingJaegerConfig))
}

// TracingProvider mocks base method
func (m *MockClientConfiguration) TracingProvider() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TracingProvider")
	ret0, _ := ret[0].(string)
	return ret0
}

// TracingProvider indicates an expected call of TracingProvider
func (mr *MockClientConfigurationMockRecorder) TracingProvider() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TracingProvider", reflect.TypeOf((*MockClientConfiguration)(nil).TracingProvider))
}

// TracingServiceName mocks base method
func (m *MockClientConfiguration) TracingServiceName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TracingServiceName")
	ret0, _ := ret[0].(string)
	return ret0
}

// TracingServiceName indicates an expected call of TracingServiceName
func (mr *MockClientConfigurationMockRecorder) TracingServiceName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TracingServiceName", reflect.TypeOf((*MockClientConfiguration)(nil).TracingServiceName))
}

// WellKnownKeys mocks base method
func (m *MockClientConfiguration) WellKnownKeys(arg0 ...string) []string {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WellKnownKeys", varargs...)
	ret0, _ := ret[0].([]string)
	return ret0
}

// WellKnownKeys indicates an expected call of WellKnownKeys
func (mr *MockClientConfigurationMockRecorder) WellKnownKeys(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WellKnownKeys", reflect.TypeOf((*MockClientConfiguration)(nil).WellKnownKeys), arg0...)
}
