/**
 * Hydra OAuth2 & OpenID Connect Server (1.0.0-aplha1)
 * Please refer to the user guide for in-depth documentation: https://ory.gitbooks.io/hydra/content/   Hydra offers OAuth 2.0 and OpenID Connect Core 1.0 capabilities as a service. Hydra is different, because it works with any existing authentication infrastructure, not just LDAP or SAML. By implementing a consent app (works with any programming language) you build a bridge between Hydra and your authentication infrastructure. Hydra is able to securely manage JSON Web Keys, and has a sophisticated policy-based access control you can use if you want to. Hydra is suitable for green- (new) and brownfield (existing) projects. If you are not familiar with OAuth 2.0 and are working on a greenfield project, we recommend evaluating if OAuth 2.0 really serves your purpose. Knowledge of OAuth 2.0 is imperative in understanding what Hydra does and how it works.   The official repository is located at https://github.com/ory/hydra   ### ATTENTION - IMPORTANT NOTE   The swagger generator used to create this documentation does currently not support example responses. To see request and response payloads click on **\"Show JSON schema\"**: ![Enable JSON Schema on Apiary](https://storage.googleapis.com/ory.am/hydra/json-schema.png)
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Session'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Session'));
  } else {
    // Browser globals (root is window)
    if (!root.HydraOAuth2OpenIdConnectServer100Aplha1) {
      root.HydraOAuth2OpenIdConnectServer100Aplha1 = {};
    }
    root.HydraOAuth2OpenIdConnectServer100Aplha1.SwaggerOAuthIntrospectionResponseBody = factory(root.HydraOAuth2OpenIdConnectServer100Aplha1.ApiClient, root.HydraOAuth2OpenIdConnectServer100Aplha1.Session);
  }
}(this, function(ApiClient, Session) {
  'use strict';




  /**
   * The SwaggerOAuthIntrospectionResponseBody model module.
   * @module model/SwaggerOAuthIntrospectionResponseBody
   * @version Latest
   */

  /**
   * Constructs a new <code>SwaggerOAuthIntrospectionResponseBody</code>.
   * in: body
   * @alias module:model/SwaggerOAuthIntrospectionResponseBody
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>SwaggerOAuthIntrospectionResponseBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SwaggerOAuthIntrospectionResponseBody} obj Optional instance to populate.
   * @return {module:model/SwaggerOAuthIntrospectionResponseBody} The populated <code>SwaggerOAuthIntrospectionResponseBody</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('active')) {
        obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
      }
      if (data.hasOwnProperty('client_id')) {
        obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
      }
      if (data.hasOwnProperty('exp')) {
        obj['exp'] = ApiClient.convertToType(data['exp'], 'Number');
      }
      if (data.hasOwnProperty('iat')) {
        obj['iat'] = ApiClient.convertToType(data['iat'], 'Number');
      }
      if (data.hasOwnProperty('scope')) {
        obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
      }
      if (data.hasOwnProperty('sess')) {
        obj['sess'] = Session.constructFromObject(data['sess']);
      }
      if (data.hasOwnProperty('sub')) {
        obj['sub'] = ApiClient.convertToType(data['sub'], 'String');
      }
      if (data.hasOwnProperty('username')) {
        obj['username'] = ApiClient.convertToType(data['username'], 'String');
      }
    }
    return obj;
  }

  /**
   * Boolean indicator of whether or not the presented token is currently active. An active token is neither refreshed nor revoked.
   * @member {Boolean} active
   */
  exports.prototype['active'] = undefined;
  /**
   * Client identifier for the OAuth 2.0 client that requested this token.
   * @member {String} client_id
   */
  exports.prototype['client_id'] = undefined;
  /**
   * Integer timestamp, measured in the number of seconds since January 1 1970 UTC, indicating when this token will expire
   * @member {Number} exp
   */
  exports.prototype['exp'] = undefined;
  /**
   * Integer timestamp, measured in the number of seconds since January 1 1970 UTC, indicating when this token was originally issued
   * @member {Number} iat
   */
  exports.prototype['iat'] = undefined;
  /**
   * A JSON string containing a space-separated list of scopes associated with this token
   * @member {String} scope
   */
  exports.prototype['scope'] = undefined;
  /**
   * @member {module:model/Session} sess
   */
  exports.prototype['sess'] = undefined;
  /**
   * Subject of the token, as defined in JWT [RFC7519]. Usually a machine-readable identifier of the resource owner who authorized this token.
   * @member {String} sub
   */
  exports.prototype['sub'] = undefined;
  /**
   * Human-readable identifier for the resource owner who authorized this token. Currently not supported by Hydra.
   * @member {String} username
   */
  exports.prototype['username'] = undefined;



  return exports;
}));


