// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// JSONPatch A JSONPatch document as defined by RFC 6902
//
// swagger:model jsonPatch
type JSONPatch struct {

	// This field is used together with operation "move" and uses JSON Pointer notation.
	//
	// Learn more [about JSON Pointers](https://datatracker.ietf.org/doc/html/rfc6901#section-5).
	// Example: /name
	From string `json:"from,omitempty"`

	// The operation to be performed. One of "add", "remove", "replace", "move", "copy", or "test".
	// Example: replace
	// Required: true
	Op *string `json:"op"`

	// The path to the target path. Uses JSON pointer notation.
	//
	// Learn more [about JSON Pointers](https://datatracker.ietf.org/doc/html/rfc6901#section-5).
	// Example: /name
	// Required: true
	Path *string `json:"path"`

	// The value to be used within the operations.
	//
	// Learn more [about JSON Pointers](https://datatracker.ietf.org/doc/html/rfc6901#section-5).
	// Example: foobar
	Value interface{} `json:"value,omitempty"`
}

// Validate validates this json patch
func (m *JSONPatch) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePath(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *JSONPatch) validateOp(formats strfmt.Registry) error {

	if err := validate.Required("op", "body", m.Op); err != nil {
		return err
	}

	return nil
}

func (m *JSONPatch) validatePath(formats strfmt.Registry) error {

	if err := validate.Required("path", "body", m.Path); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this json patch based on context it is used
func (m *JSONPatch) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JSONPatch) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JSONPatch) UnmarshalBinary(b []byte) error {
	var res JSONPatch
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
