// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// NullDuration NullDuration represents a nullable JSON and SQL compatible time.Duration.
//
// TODO delete this type and replace it with ory/x/sqlxx/NullDuration when applying the custom client token TTL patch to Hydra 2.x
//
// swagger:model NullDuration
type NullDuration string

// Validate validates this null duration
func (m NullDuration) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this null duration based on context it is used
func (m NullDuration) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
