// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// StringSlicePipeDelimiter StringSlicePipeDelimiter de/encodes the string slice to/from a SQL string.
//
// swagger:model StringSlicePipeDelimiter
type StringSlicePipeDelimiter []string

// Validate validates this string slice pipe delimiter
func (m StringSlicePipeDelimiter) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this string slice pipe delimiter based on context it is used
func (m StringSlicePipeDelimiter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
