#!/usr/bin/env bash
# Called by bridg/bridg make lifecycle tasks on post-system-start.
#

echo "Running hydra client seeding."
docker-compose run --rm --no-deps --entrypoint \
  "/go/bin/hydra clients import
     data/clients/bridg-admin.json
     data/clients/bridg-analytics.json
     data/clients/bridg-api-gateway.json
     data/clients/bridg-iam.json
     data/clients/bridg-insights.json
     data/clients/bridg-login.json
     data/clients/bridg-www.json" \
  web

echo "Running hydra group seeding."
docker-compose run --rm --no-deps --entrypoint \
  "/go/bin/hydra groups create bridg-admin" \
  web
docker-compose run --rm --no-deps --entrypoint \
  "/go/bin/hydra groups members add bridg-admin
    2c815dbe-a6b2-40a3-b32f-4cc39a1f62f2
    f3988105-e618-4dfc-80ca-dafae74d6242
    111f3c54-4d88-4518-b044-2f28f2600a13
    467d12a8-e43f-409d-85ef-bc556062f116
    40f15f9e-d7c3-47dc-9843-6ff0c8c6e58d" \
  web
docker-compose run --rm --no-deps --entrypoint \
  "/go/bin/hydra groups create account-admin" \
  web
docker-compose run --rm --no-deps --entrypoint \
  "/go/bin/hydra groups members add account-admin
    4dfadb9f-8f73-4b21-b166-90bac7fac555" \
  web

echo "Running hydra policy seeding."
docker-compose run --rm --no-deps --entrypoint \
  "/go/bin/hydra policies create -f data/policies/account-admin.json &&
   /go/bin/hydra policies create -f data/policies/account-admin-deny.json &&
   /go/bin/hydra policies create -f data/policies/account-viewer.json &&
   /go/bin/hydra policies create -f data/policies/bridg-admin.json &&
   /go/bin/hydra policies create -f data/policies/bridg-admin-search.json &&
   /go/bin/hydra policies create -f data/policies/bridg-analytics.json &&
   /go/bin/hydra policies create -f data/policies/bridg-api-gateway.json &&
   /go/bin/hydra policies create -f data/policies/bridg-iam.json &&
   /go/bin/hydra policies create -f data/policies/bridg-login.json &&
   /go/bin/hydra policies create -f data/policies/elastic-search.json &&
   /go/bin/hydra policies create -f data/policies/elastic-search-deny.json &&
   /go/bin/hydra policies create -f data/policies/metrics-viewer.json &&
   /go/bin/hydra policies create -f data/policies/reveal-deny.json" \
  web

